template-file-path: main.yaml
parameters:
  PrivateSubnet1Cidr: 10.0.2.0/24
  AllowedGithubRepo: Bassell-Iddisah/ECS-CI-DC-Lab-Infra
  PublicSubnet2Cidr: 10.0.1.0/24
  VpcCidr: 10.0.0.0/16
  EnvironmentName: cicd-lab-stack
  PrivateSubnet2Cidr: 10.0.3.0/24
  AllowedGithubBranch: refs/heads/main
  AppPort: '80'
  DeploymentZipFileName: app.zip
  PublicSubnet1Cidr: 10.0.0.0/24
tags: {}
